#!/usr/bin/env python3
from configparser import ConfigParser
from os.path import expanduser
import subprocess
import sys

config = ConfigParser()
config.read(expanduser("~/.gitprofile"))

def usage():
    print("usage: git profile <command> <parameters>")
    print("Available commands:")
    print("   List available profiles:     list")
    print("   Set active profile:          use <profilename>")
    sys.exit(1)

if len(sys.argv) == 1:
    print("error: missing command")
    usage()

cmd = sys.argv[1]

if cmd == "list":
    print("Available profiles:")
    for profile in config.sections():
        print("  %s" % profile)
elif cmd == "use":
    section = sys.argv[2]

    if not config.has_section(section):
        print(("Profile %s not found" % section))
        sys.exit(1)
    else:
        subprocess.call(["git", "config", "--local", "user.name", config.get(section, "name")])
        subprocess.call(["git", "config", "--local", "user.email", config.get(section, "email")])
        print("Set user to %s <%s>" % (config.get(section, "name"), config.get(section, "email")))
else:
    print("error: unkown command `%s`" % cmd)
    usage()
