#!/usr/bin/env python
from ConfigParser import SafeConfigParser
from os.path import expanduser
import subprocess
import sys

config = SafeConfigParser()
config.read(expanduser("~/.gitprofile"))

if len(sys.argv) == 1:
    print "Missing action."
    sys.exit(1)

action = sys.argv[1]

if action == "list":
    print "Available profiles:"
    for profile in config.sections():
        print "  %s" % profile
elif action == "use":
    section = sys.argv[2]

    if not config.has_section(section):
        print("Profile %s not found" % section)
        sys.exit(1)
    else:
        subprocess.call(["git", "config", "--local", "user.name", config.get(section, "name")])
        subprocess.call(["git", "config", "--local", "user.email", config.get(section, "email")])
        print "Set user to %s <%s>" % (config.get(section, "name"), config.get(section, "email"))
